prowjob_namespace: default
pod_namespace: test-pods

plank:
  job_url_prefix_config:
    '*': https://prow.apps.ci.metal3.io/view/gcs/
  default_decoration_configs:
    '*':
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20201030-914f29394d"
        initupload: "gcr.io/k8s-prow/initupload:v20201030-914f29394d"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20201030-914f29394d"
        sidecar: "gcr.io/k8s-prow/sidecar:v20201030-914f29394d"
      gcs_configuration:
        bucket: metal3-prow-artifacts
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials

tide:
  merge_method:
    metal3-io/project-config: merge
  queries:
  - repos:
    - metal3-io/baremetal-operator
    - metal3-io/base-image
    - metal3-io/cluster-api-provider-metal3
    - metal3-io/ironic-hardware-inventory-recorder-image
    - metal3-io/ironic-image
    - metal3-io/ironic-inspector-image
    - metal3-io/ironic-ipa-downloader
    - metal3-io/ironic-prometheus-exporter
    - metal3-io/metal3-dev-env
    - metal3-io/metal3-docs
    - metal3-io/metal3-helm-chart
    - metal3-io/metal3-io.github.io
    - metal3-io/metal3-smart-exporter
    - metal3-io/project-infra
    - metal3-io/static-ip-manager-image
    - metal3-io/ip-address-manager
    - metal3-io/hardware-classification-controller
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
  context_options:
    # Use branch protection options to define required and optional contexts
    from-branch-protection: true

#
# Use prow to manage the configuration of github branch protection.
# This is what controls which github status checks (or CI jobs) must
# be passing for a PR to merge.
#
# Docs: https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector
#
branch-protection:
  orgs:
    metal3-io:
      # Require "always_run: true" jobs to pass before merging.
      # To turn this off for a given job, set "optional: true"
      # in the job definition.
      protect: true
      repos:
        baremetal-operator:
          # Use this to specify that a status coming from outside of prow is
          # required.  We use this to require functional jobs running in
          # jenkins are required, for example.
          required_status_checks:
            contexts: ["test-integration"]
        cluster-api-provider-metal3:
          branches:
            master:
              required_status_checks:
                contexts: ["test-integration"]
            release-0.3:
              required_status_checks:
                contexts: ["test-v1a3-integration"]
        ironic-image:
          required_status_checks:
            contexts: ["test-integration"]
        ironic-inspector-image:
          required_status_checks:
            contexts: ["test-integration"]
        ironic-ipa-downloader:
          required_status_checks:
            contexts: ["test-integration"]
        ip-address-manager:
          required_status_checks:
            contexts: ["test-integration"]
        metal3-dev-env:
          required_status_checks:
            contexts: ["test-centos-integration", "test-integration"]

deck:
  spyglass:
    viewers:
      "started.json|finished.json":
      - "metadata"
      "build-log.txt|clone-log.txt":
      - "buildlog"

periodics:
 - name: periodic-stale
   interval: 1h
   decorate: true
   spec:
     containers:
     - image: gcr.io/k8s-prow/commenter:v20201030-914f29394d
       command:
       - /app/robots/commenter/app.binary
       args:
       - |-
         --query=org:metal3-io
         -label:lifecycle/frozen
         -label:lifecycle/stale
       - --updated=2160h
       - --token=/etc/token/oauth
       - |-
         --comment=Issues go stale after 90d of inactivity.
         Mark the issue as fresh with `/remove-lifecycle stale`.
         Stale issues will close after an additional 30d of inactivity.

         If this issue is safe to close now please do so with `/close`.

         /lifecycle stale
       - --template
       - --ceiling=10
       - --confirm
       volumeMounts:
       - name: token
         mountPath: /etc/token
     volumes:
     - name: token
       secret:
         secretName: oauth-token
 - name: periodic-stale-close
   interval: 1h
   decorate: true
   spec:
     containers:
     - image: gcr.io/k8s-prow/commenter:v20201030-914f29394d
       command:
       - /app/robots/commenter/app.binary
       args:
       - |-
         --query=org:metal3-io
         -label:lifecycle/frozen
         label:lifecycle/stale
       - --updated=720h
       - --token=/etc/token/oauth
       - |-
         --comment=Stale issues close after 30d of inactivity. Reopen the issue with `/reopen`. Mark the issue as fresh with `/remove-lifecycle stale`.

         /close
       - --template
       - --ceiling=10
       - --confirm
       volumeMounts:
       - name: token
         mountPath: /etc/token
     volumes:
     - name: token
       secret:
         secretName: oauth-token
 - name: ci-prow-autobump
   # https://github.com/kubernetes/test-infra/tree/master/prow/cmd/autobump#prow-autobump
   # https://github.com/kubernetes/test-infra/blob/master/prow/cmd/autobump/example-periodic.yaml
   cron: "05 15-23 * * 1-5"  # Run at 7:05-15:05 PST (15:05 UTC) Mon-Fri
   decorate: true
   extra_refs:
   # Check out the repo containing the config and deployment files for your Prow instance.
   - org: metal3-io
     repo: project-infra
     base_ref: master
   spec:
     containers:
     - image: gcr.io/k8s-prow/autobump # TODO: add a tag once we've push this the first time.
       command:
       - /autobump.sh
       args:
       - /etc/github-token/oauth
       # Make the bot name and email match the user data of the provided token's user.
       - "metal3-io-bot"
       - metal3.io.bot@gmail.com
       volumeMounts:
       - name: github
         mountPath: /etc/github-token
         readOnly: true
       env:
     # autobump.sh args
       # GitHub org containing the repo where the Prow config and component files live.
       - name: GH_ORG
         value: metal3-io
       # GitHub repo where the Prow config and component deployment files live.
       - name: GH_REPO
         value: project-infra
       # Repo relative path of the `plank` component k8s deployment file.
       - name: PLANK_DEPLOYMENT_FILE
         value: prow/manifests/plank-deployment.yaml
     # bump.sh args
       # Directory (or comma-delimited list of directories) containing k8s deployment YAMLs for Prow components.
       - name: COMPONENT_FILE_DIR
         value: prow/manifests
       # Repo relative path of the core Prow config file (config.yaml).
       - name: CONFIG_PATH
         value: prow/config/config.yaml
       # Repo relative path of the ProwJob config file or directory.
       # Omit this if ProwJobs are only defined in config.yaml (or are not configured at all).
       #- name: JOB_CONFIG_PATH
       #  value: config/jobs
     volumes:
     - name: github
       secret:
         # Secret containing a GitHub user access token with `repo` scope for creating PRs.
         secretName: oauth-token

presubmits:
  metal3-io/baremetal-operator:
  - name: gofmt
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/gofmt.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: gosec
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/gosec.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/securego/gosec:latest
        imagePullPolicy: Always
  - name: govet
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/govet.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: gomod
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/gomod.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: markdownlint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/pipelinecomponents/markdownlint:latest
        imagePullPolicy: Always
  - name: shellcheck
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: koalaman/shellcheck-alpine:stable
        imagePullPolicy: Always
  - name: unit
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/unit.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        - name: DEPLOY_KERNEL_URL
          value: "http://172.22.0.1/images/ironic-python-agent.kernel"
        - name: DEPLOY_RAMDISK_URL
          value: "http://172.22.0.1/images/ironic-python-agent.initramfs"
        - name: IRONIC_ENDPOINT
          value: "http://localhost:6385/v1/"
        - name: IRONIC_INSPECTOR_ENDPOINT
          value: "http://localhost:5050/v1/"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: generate
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/generate.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        - name: DEPLOY_KERNEL_URL
          value: "http://172.22.0.1/images/ironic-python-agent.kernel"
        - name: DEPLOY_RAMDISK_URL
          value: "http://172.22.0.1/images/ironic-python-agent.initramfs"
        - name: IRONIC_ENDPOINT
          value: "http://localhost:6385/v1/"
        - name: IRONIC_INSPECTOR_ENDPOINT
          value: "http://localhost:5050/v1/"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: golint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/golint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/golint:latest
        imagePullPolicy: Always

  metal3-io/cluster-api-provider-metal3:
  - name: gofmt
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/gofmt.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always
  - name: golint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/golint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always
  - name: govet
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/govet.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always
  - name: markdownlint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/pipelinecomponents/markdownlint:latest
        imagePullPolicy: Always
  - name: shellcheck
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: koalaman/shellcheck-alpine:stable
        imagePullPolicy: Always
  - name: generate
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/codegen.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always
  - name: unit
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/unit.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always

  metal3-io/metal3-dev-env:
  - name: shellcheck
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: koalaman/shellcheck-alpine:stable
        imagePullPolicy: Always
  - name: markdownlint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/pipelinecomponents/markdownlint:latest
        imagePullPolicy: Always

  metal3-io/project-infra:
  - name: check-prow-config
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20201030-914f29394d
        args:
        - "/checkconfig"
        - "--config-path"
        - "prow/config/config.yaml"
        - "--plugin-config"
        - "prow/config/plugins.yaml"
        - "--strict"
        resources:
          requests:
            memory: "500Mi"
  metal3-io/metal3-docs:
  - name: markdownlint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/pipelinecomponents/markdownlint:latest
        imagePullPolicy: Always

  metal3-io/ip-address-manager:
  - name: gofmt
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/gofmt.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: govet
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/govet.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: markdownlint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/pipelinecomponents/markdownlint:latest
        imagePullPolicy: Always
  - name: shellcheck
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: koalaman/shellcheck-alpine:stable
        imagePullPolicy: Always
  - name: unit
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/unit.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always
  - name: generate
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/codegen.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always

  metal3-io/hardware-classification-controller:
  - name: gofmt
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/gofmt.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: govet
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/govet.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/library/golang:1.15.3
        imagePullPolicy: Always
  - name: markdownlint
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: registry.hub.docker.com/pipelinecomponents/markdownlint:latest
        imagePullPolicy: Always
  - name: shellcheck
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: koalaman/shellcheck-alpine:stable
        imagePullPolicy: Always
  - name: unit
    always_run: true
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/unit.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/capm3-unit:master
        imagePullPolicy: Always
